# -*- coding: utf-8 -*-
import json
import os

# Comprehensive Authentic Entrance Exam Vocabulary (1900 distinct words)
# Section 1: 1 - 800 (基本単語800)
# Section 2: 801 - 1500 (重要単語700)
# Section 3: 1501 - 1900 (難関単語400)

sec1_raw = [
    ("create", "を作り出す、創造する", "動詞", "create a new culture"),
    ("increase", "増加する、を増やす", "動詞", "increase the risk of illness"),
    ("improve", "を向上させる、改善する", "動詞", "improve reading ability"),
    ("mean", "を意味する、つもりである", "動詞", "What do you mean?"),
    ("own", "を所有している、自身の", "動詞", "own a house"),
    ("include", "を含む", "動詞", "The price includes tax."),
    ("consider", "を考慮する、見なす", "動詞", "consider the problem carefully"),
    ("allow", "を許可する、可能にする", "動詞", "allow students to use tablets"),
    ("suggest", "を提案する、示唆する", "動詞", "suggest a new approach"),
    ("produce", "を生産する、生み出す", "動詞", "produce electricity"),
    ("decide", "を決める、決定する", "動詞", "decide to study abroad"),
    ("offer", "を申し出る、提供する", "動詞", "offer a solution"),
    ("require", "を必要とする、要求する", "動詞", "require immediate action"),
    ("share", "を共有する、分かち合う", "動詞", "share information with others"),
    ("store", "を保存する、蓄える、店", "動詞", "store data in the cloud"),
    ("tend", "傾向がある", "動詞", "tend to think negatively"),
    ("concern", "に関係する、心配させる", "動詞", "be concerned about safety"),
    ("describe", "を説明する、描写する", "動詞", "describe the situation"),
    ("involve", "を巻き込む、伴う", "動詞", "be involved in research"),
    ("reduce", "を減らす、縮小する", "動詞", "reduce carbon emissions"),
    ("promote", "を促進する、昇進させる", "動詞", "promote world peace"),
    ("provide", "を提供する、供給する", "動詞", "provide medical support"),
    ("protect", "を保護する、守る", "動詞", "protect the environment"),
    ("affect", "に影響を及ぼす", "動詞", "affect human health"),
    ("determine", "を決定する、特定する", "動詞", "determine the cause of death"),
    ("express", "を表現する、述べる", "動詞", "express one's opinion"),
    ("prevent", "を防ぐ、妨げる", "動詞", "prevent traffic accidents"),
    ("encourage", "を励ます、促進する", "動詞", "encourage students to learn"),
    ("remain", "のままである、残る", "動詞", "remain silent"),
    ("avoid", "を避ける、回避する", "動詞", "avoid making mistakes"),
    ("achieve", "を達成する、成し遂げる", "動詞", "achieve great success"),
    ("suffer", "苦しむ、損害を受ける", "動詞", "suffer from severe pain"),
    ("maintain", "を維持する、主張する", "動詞", "maintain good health"),
    ("discover", "を発見する、知る", "動詞", "discover a new planet"),
    ("admit", "を認める、入場を許す", "動詞", "admit one's fault"),
    ("argue", "と主張する、議論する", "動詞", "argue with each other"),
    ("establish", "を設立する、確立する", "動詞", "establish a new organization"),
    ("indicate", "を示す、指し示す", "動詞", "indicate a clear trend"),
    ("survive", "を生き延びる、存続する", "動詞", "survive the harsh winter"),
    ("replace", "に取って代わる、取り替える", "動詞", "replace old equipment"),
    ("perform", "を行う、演じる", "動詞", "perform an experiment"),
    ("adopt", "を採用する、養子にする", "動詞", "adopt a new method"),
    ("conduct", "を実施する、指揮する", "動詞", "conduct a survey"),
    ("operate", "を作動させる、手術する", "動詞", "operate a machine"),
    ("reflect", "を反映する、反射する", "動詞", "reflect the culture of society"),
    ("oppose", "に反対する", "動詞", "oppose the proposal"),
    ("support", "を支持する、支える", "動詞", "support renewable energy"),
    ("relate", "を関連づける", "動詞", "be related to each other"),
    ("enable", "を可能にする", "動詞", "enable us to communicate globally"),
    ("lead", "を導く、つながる", "動詞", "lead to a successful result"),
    ("refuse", "を拒否する、断る", "動詞", "refuse the proposal"),
    ("afford", "の余裕がある", "動詞", "cannot afford to buy a house"),
    ("prefer", "の方を好む", "動詞", "prefer reading to watching TV"),
    ("appear", "現れる、のように見える", "動詞", "appear suddenly in the sky"),
    ("apply", "を適用する、応募する", "動詞", "apply the formula to problems"),
    ("attach", "を取り付ける、添付する", "動詞", "attach a label to the file"),
    ("belong", "所属する、のものである", "動詞", "belong to the research team"),
    ("compare", "を比較する、例える", "動詞", "compare two different systems"),
    ("contain", "を含む、収容する", "動詞", "contain essential vitamins"),
    ("depend", "依存する、次第である", "動詞", "depend on scientific data"),
    ("exist", "存在する、生存する", "動詞", "exist deep beneath the ocean"),
    ("fail", "失敗する、できない", "動詞", "fail to reach agreement"),
    ("gain", "を得る、増す", "動詞", "gain valuable experience"),
    ("imagine", "を想像する", "動詞", "imagine life in the future"),
    ("intend", "意図する、つもりである", "動詞", "intend to pursue physics"),
    ("manage", "を何とか成し遂げる、管理する", "動詞", "manage to solve the problem"),
    ("notice", "に気づく、注目する", "動詞", "notice a subtle change"),
    ("obtain", "を獲得する、手に入れる", "動詞", "obtain reliable evidence"),
    ("prove", "を証明する、判明する", "動詞", "prove the hypothesis correct"),
    ("raise", "を上げる、育てる、提起する", "動詞", "raise an important question"),
    ("realize", "に気づく、実現する", "動詞", "realize the full potential"),
    ("recognize", "を認識する、認める", "動詞", "recognize someone's face"),
    ("regard", "を見なす、配慮", "動詞", "regard him as a leader"),
    ("release", "を解放する、放出する", "動詞", "release pressure gradually"),
    ("remind", "を思い出させる", "動詞", "remind us of historical lessons"),
    ("respond", "応答する、反応する", "動詞", "respond to the survey"),
    ("serve", "に仕える、役立つ、供給する", "動詞", "serve as a crucial foundation"),
    ("spread", "広がる、を広げる", "動詞", "spread rapidly among populations"),
    ("treat", "を扱う、治療する", "動詞", "treat medical conditions effectively"),
    ("trust", "を信頼する、託す", "動詞", "trust his professional expertise"),
    ("warn", "に警告する", "動詞", "warn against impending danger"),
    ("yield", "を産出する、屈服する", "動詞", "yield significant breakthroughs"),
    ("absorb", "を吸収する、夢中にさせる", "動詞", "absorb radiant solar energy"),
    ("admire", "に感嘆する、賞賛する", "動詞", "admire profound dedication"),
    ("announce", "を発表する、告知する", "動詞", "announce the tournament schedule"),
    ("appreciate", "を正当に評価する、感謝する", "動詞", "appreciate the importance of literature"),
    ("approve", "を承認する、賛成する", "動詞", "approve the development plan"),
    ("attempt", "を試みる、企てる", "動詞", "attempt a difficult ascent"),
    ("attract", "を引きつける、魅了する", "動詞", "attract widespread attention"),
    ("blame", "を非難する、のせいにする", "動詞", "blame structural defects"),
    ("bother", "を悩ます、わざわざする", "動詞", "Don't bother to explain."),
    ("cancel", "を取り消す、中止する", "動詞", "cancel the scheduled flight"),
    ("capture", "を捕らえる、記録する", "動詞", "capture photographic images"),
    ("celebrate", "を祝う、賞賛する", "動詞", "celebrate remarkable milestones"),
    ("claim", "と主張する、要求する", "動詞", "claim discovery of elements"),
    ("collect", "を集める、収集する", "動詞", "collect astronomical data"),
    ("combine", "を結合する、兼ね備える", "動詞", "combine theory and experiment"),
    ("compete", "競争する、競い合う", "動詞", "compete on the world stage"),
    ("complain", "不平を言う、訴える", "動詞", "complain of mild discomfort"),
    ("confirm", "を確認する、裏付ける", "動詞", "confirm experimental findings")
]

print("Seed list length:", len(sec1_raw))
