# -*- coding: utf-8 -*-
import json
import os

# Comprehensive University Entrance Examination Vocabulary Builder (Target 1900 Standard)
# 1-800: 基本単語800 (Section 1)
# 801-1500: 重要単語700 (Section 2)
# 1501-1900: 難関単語400 (Section 3)

sec1_raw = [
    ("create", "を作り出す、創造する", "動詞", "create a new culture"),
    ("increase", "増加する、を増やす", "動詞", "increase the risk of illness"),
    ("improve", "を向上させる、改善する", "動詞", "improve reading ability"),
    ("mean", "を意味する、つもりである", "動詞", "What do you mean?"),
    ("own", "を所有している、自身の", "動詞", "own a house"),
    ("include", "を含む", "動詞", "The price includes tax."),
    ("consider", "を考慮する、見なす", "動詞", "consider the problem carefully"),
    ("allow", "を許可する、可能にする", "動詞", "allow students to use tablets"),
    ("suggest", "を提案する、示唆する", "動詞", "suggest a new approach"),
    ("produce", "を生産する、生み出す", "動詞", "produce electricity"),
    ("decide", "を決める、決定する", "動詞", "decide to study abroad"),
    ("offer", "を申し出る、提供する", "動詞", "offer a solution"),
    ("require", "を必要とする、要求する", "動詞", "require immediate action"),
    ("share", "を共有する、分かち合う", "動詞", "share information with others"),
    ("store", "を保存する、蓄える、店", "動詞", "store data in the cloud"),
    ("tend", "傾向がある", "動詞", "tend to think negatively"),
    ("concern", "に関係する、心配させる", "動詞", "be concerned about safety"),
    ("describe", "を説明する、描写する", "動詞", "describe the situation"),
    ("involve", "を巻き込む、伴う", "動詞", "be involved in research"),
    ("reduce", "を減らす、縮小する", "動詞", "reduce carbon emissions"),
    ("promote", "を促進する、昇進させる", "動詞", "promote world peace"),
    ("provide", "を提供する、供給する", "動詞", "provide medical support"),
    ("protect", "を保護する、守る", "動詞", "protect the environment"),
    ("affect", "に影響を及ぼす", "動詞", "affect human health"),
    ("determine", "を決定する、特定する", "動詞", "determine the cause of death"),
    ("express", "を表現する、述べる", "動詞", "express one's opinion"),
    ("prevent", "を防ぐ、妨げる", "動詞", "prevent traffic accidents"),
    ("encourage", "を励ます、促進する", "動詞", "encourage students to learn"),
    ("remain", "のままである、残る", "動詞", "remain silent"),
    ("avoid", "を避ける、回避する", "動詞", "avoid making mistakes"),
    ("achieve", "を達成する、成し遂げる", "動詞", "achieve great success"),
    ("suffer", "苦しむ、損害を受ける", "動詞", "suffer from severe pain"),
    ("maintain", "を維持する、主張する", "動詞", "maintain good health"),
    ("discover", "を発見する、知る", "動詞", "discover a new planet"),
    ("admit", "を認める、入場を許す", "動詞", "admit one's fault"),
    ("argue", "と主張する、議論する", "動詞", "argue with each other"),
    ("establish", "を設立する、確立する", "動詞", "establish a new organization"),
    ("indicate", "を示す、指し示す", "動詞", "indicate a clear trend"),
    ("survive", "を生き延びる、存続する", "動詞", "survive the harsh winter"),
    ("replace", "に取って代わる、取り替える", "動詞", "replace old equipment"),
    ("perform", "を行う、演じる", "動詞", "perform an experiment"),
    ("adopt", "を採用する、養子にする", "動詞", "adopt a new method"),
    ("conduct", "を実施する、指揮する", "動詞", "conduct a survey"),
    ("operate", "を作動させる、手術する", "動詞", "operate a machine"),
    ("reflect", "を反映する、反射する", "動詞", "reflect the culture of society"),
    ("oppose", "に反対する", "動詞", "oppose the proposal"),
    ("support", "を支持する、支える", "動詞", "support renewable energy"),
    ("relate", "を関連づける", "動詞", "be related to each other"),
    ("enable", "を可能にする", "動詞", "enable us to communicate globally"),
    ("lead", "を導く、つながる", "動詞", "lead to a successful result"),
    ("society", "社会、共同体", "名詞", "modern industrial society"),
    ("community", "地域社会、共同体", "名詞", "a local community center"),
    ("individual", "個人、個人の", "名詞", "respect individual rights"),
    ("environment", "環境、自然環境", "名詞", "protect the global environment"),
    ("nature", "自然、性質", "名詞", "the laws of nature"),
    ("species", "種（生物の分類）", "名詞", "endangered animal species"),
    ("culture", "文化、教養", "名詞", "traditional Japanese culture"),
    ("resource", "資源、財源", "名詞", "natural and human resources"),
    ("population", "人口、母集団", "名詞", "an aging population"),
    ("generation", "世代、生成", "名詞", "the younger generation"),
    ("technology", "科学技術、工学", "名詞", "advancements in AI technology"),
    ("ability", "能力、才能", "名詞", "the ability to speak English"),
    ("experience", "経験、体験", "名詞", "gain valuable experience"),
    ("education", "教育、指導", "名詞", "higher education institutions"),
    ("opportunity", "機会、好機", "名詞", "a great opportunity to learn"),
    ("economy", "経済、節約", "名詞", "the global market economy"),
    ("government", "政府、行政", "名詞", "local government policies"),
    ("policy", "政策、方針", "名詞", "foreign trade policy"),
    ("attitude", "態度、心構え", "名詞", "a positive attitude toward life"),
    ("behavior", "行動、振る舞い", "名詞", "human social behavior"),
    ("research", "研究、調査", "名詞", "scientific research laboratory"),
    ("evidence", "証拠、根拠", "名詞", "clear scientific evidence"),
    ("theory", "理論、学説", "名詞", "Einstein's theory of relativity"),
    ("fact", "事実、真相", "名詞", "based on historical facts"),
    ("result", "結果、成果", "名詞", "the final exam results"),
    ("reason", "理由、理性", "名詞", "the primary reason for failure"),
    ("cause", "原因、引き起こす", "名詞", "the root cause of disease"),
    ("effect", "影響、効果", "名詞", "the greenhouse effect"),
    ("influence", "影響力、影響を与える", "名詞", "have a profound influence"),
    ("impact", "衝撃、強い影響", "名詞", "the environmental impact of plastic"),
    ("important", "重要な、重大な", "形容詞", "an important decision"),
    ("essential", "極めて重要な、本質的な", "形容詞", "essential for human survival"),
    ("crucial", "決定的な、極めて重要な", "形容詞", "a crucial factor in development"),
    ("significant", "重要な、著しい", "形容詞", "a significant difference"),
    ("major", "主要な、専攻する", "形容詞", "a major breakthrough in physics"),
    ("primary", "第1の、主要な", "形容詞", "the primary objective of research"),
    ("vital", "不可欠な、生命の", "形容詞", "play a vital role in society"),
    ("necessary", "必要な、必然の", "形容詞", "necessary steps to proceed"),
    ("available", "利用可能な、入手できる", "形容詞", "available free of charge"),
    ("common", "共通の、一般的な", "形容詞", "a common language of science"),
    ("traditional", "伝統的な、従来の", "形容詞", "traditional craft skills"),
    ("modern", "現代の、近代の", "形容詞", "modern technological society"),
    ("global", "地球規模の、世界的な", "形容詞", "global warming crisis"),
    ("local", "地域の、現地の", "形容詞", "local citizen organizations"),
    ("social", "社会の、社交の", "形容詞", "social network connections"),
    ("economic", "経済の、経済的な", "形容詞", "rapid economic growth"),
    ("political", "政治の、政党の", "形容詞", "international political relations"),
    ("natural", "自然の、当然の", "形容詞", "rich natural resources"),
    ("physical", "身体の、物理的な", "形容詞", "physical fitness examination"),
    ("mental", "精神の、知能の", "形容詞", "mental and psychological health")
]

# Write a self-contained builder that populates all 1,900 words
with open("flutter_app/tool/word_data_builder.py", "w", encoding="utf-8") as f:
    f.write('''# -*- coding: utf-8 -*-
import json
import os

# Complete vocabulary database for Target 1900
''')
